import imgAdventurePhotographer from '../assets/images/adventure-photographer.png'
import imgBakeryShop from '../assets/images/bakery-shop.png'
import imgBarberShop from '../assets/images/barber-shop.png'
import imgCoffeeShop from '../assets/images/coffee-shop.png'
import imgCorporatePortfolio from '../assets/images/corporate-portfolio.png'
import imgCreativePortfolio from '../assets/images/creative-portfolio.png'
import imgDentalClinic from '../assets/images/dental-clinic.png'
import imgDiningRestaurant from '../assets/images/dining-restaurant.png'
import imgElectricianContractor from '../assets/images/electrician-contractor.png'
import imgFitnessTrainer from '../assets/images/fitness-trainer.png'
import imgHomeCleaningService from '../assets/images/home-cleaning-service.png'
import imgHvacTechnician from '../assets/images/hvac-technician.png'
import imgItConsultant from '../assets/images/it-consultant.png'
import imgLandscapeContractor from '../assets/images/landscape-contractor.png'
import imgLuxuryPlumbing from '../assets/images/luxury-plumbing.png'
import imgRealEstateAgent from '../assets/images/real-estate-agent.png'
import imgSnowRemoval from '../assets/images/snow-removal.png'
import imgStudentResume from '../assets/images/student-resume.png'

const BASE = import.meta.env.BASE_URL

export const templateFilters = ['All', 'Resume', 'Portfolio', 'Business', 'Services']

export const templateSortOptions = ['Most Popular', 'Newest', 'Recommended']

export const templates = [
  // ── Resume ──────────────────────────────────────────────────────────────
  {
    id: 'student-resume',
    title: 'Student Resume',
    category: 'Resume Templates',
    filterCategory: 'Resume',
    tags: ['Resume', 'Student', 'Entry Level', 'Modern'],
    shortDescription: 'Clean, modern single-page resume for students and recent graduates.',
    thumbnail: imgStudentResume,
    demoUrl: `${BASE}templates/spa/student-resume.html`,
    type: 'spa-html',
    popularity: 91,
    createdAt: '2026-04-18',
    recommended: true,
  },
  {
    id: 'it-consultant',
    title: 'IT Consultant',
    category: 'Resume Templates',
    filterCategory: 'Resume',
    tags: ['Resume', 'IT', 'Consulting', 'Professional'],
    shortDescription: 'Professional resume and service showcase for IT consultants and technology experts.',
    thumbnail: imgItConsultant,
    demoUrl: `${BASE}templates/spa/it-consultant.html`,
    type: 'spa-html',
    popularity: 88,
    createdAt: '2026-04-18',
    recommended: true,
  },

  // ── Portfolio ────────────────────────────────────────────────────────────
  {
    id: 'adventure-photographer',
    title: 'Adventure Photographer Portfolio',
    category: 'Portfolio Templates',
    filterCategory: 'Portfolio',
    tags: ['Portfolio', 'Photography', 'Creative', 'Visual'],
    shortDescription: 'Bold, immersive portfolio for adventure and landscape photographers.',
    thumbnail: imgAdventurePhotographer,
    demoUrl: `${BASE}templates/spa/adventure-photographer.html`,
    type: 'spa-html',
    popularity: 94,
    createdAt: '2026-04-18',
    recommended: true,
  },
  {
    id: 'corporate-portfolio',
    title: 'Corporate Portfolio',
    category: 'Portfolio Templates',
    filterCategory: 'Portfolio',
    tags: ['Portfolio', 'Corporate', 'Consulting', 'Professional'],
    shortDescription: 'Polished corporate portfolio for consultants and business professionals.',
    thumbnail: imgCorporatePortfolio,
    demoUrl: `${BASE}templates/spa/corporate-portfolio.html`,
    type: 'spa-html',
    popularity: 87,
    createdAt: '2026-04-18',
    recommended: false,
  },
  {
    id: 'creative-portfolio',
    title: 'Creative Portfolio',
    category: 'Portfolio Templates',
    filterCategory: 'Portfolio',
    tags: ['Portfolio', 'Creative', 'Design', 'Visual'],
    shortDescription: 'Expressive creative portfolio for designers, artists, and creative professionals.',
    thumbnail: imgCreativePortfolio,
    demoUrl: `${BASE}templates/spa/creative-portfolio.html`,
    type: 'spa-html',
    popularity: 96,
    createdAt: '2026-04-18',
    recommended: true,
  },

  // ── Business ─────────────────────────────────────────────────────────────
  {
    id: 'barber-shop',
    title: 'Barber Shop',
    category: 'Business Templates',
    filterCategory: 'Business',
    tags: ['Business', 'Barbershop', 'Grooming', 'Local'],
    shortDescription: "Bold, modern website for premium barber shops and men's grooming studios.",
    thumbnail: imgBarberShop,
    demoUrl: `${BASE}templates/spa/barber-shop.html`,
    type: 'spa-html',
    popularity: 85,
    createdAt: '2026-04-18',
    recommended: false,
  },
  {
    id: 'bakery-shop',
    title: 'Bakery & Pastry Shop',
    category: 'Business Templates',
    filterCategory: 'Business',
    tags: ['Business', 'Bakery', 'Food', 'Local'],
    shortDescription: 'Warm and inviting website for artisan bakeries and pastry shops.',
    thumbnail: imgBakeryShop,
    demoUrl: `${BASE}templates/spa/bakery-shop.html`,
    type: 'spa-html',
    popularity: 82,
    createdAt: '2026-04-18',
    recommended: false,
  },
  {
    id: 'coffee-shop',
    title: 'Artisan Coffee Shop',
    category: 'Business Templates',
    filterCategory: 'Business',
    tags: ['Business', 'Coffee', 'Cafe', 'Food & Beverage'],
    shortDescription: 'Cozy and elegant website template for artisan coffee shops and cafes.',
    thumbnail: imgCoffeeShop,
    demoUrl: `${BASE}templates/spa/coffee-shop.html`,
    type: 'spa-html',
    popularity: 89,
    createdAt: '2026-04-18',
    recommended: true,
  },
  {
    id: 'dental-clinic',
    title: 'Dental Clinic',
    category: 'Business Templates',
    filterCategory: 'Business',
    tags: ['Business', 'Dental', 'Healthcare', 'Clinic'],
    shortDescription: 'Clean, trustworthy website for dental clinics and healthcare practices.',
    thumbnail: imgDentalClinic,
    demoUrl: `${BASE}templates/spa/dental-clinic.html`,
    type: 'spa-html',
    popularity: 83,
    createdAt: '2026-04-18',
    recommended: false,
  },
  {
    id: 'dining-restaurant',
    title: 'Fine Dining Restaurant',
    category: 'Business Templates',
    filterCategory: 'Business',
    tags: ['Business', 'Restaurant', 'Fine Dining', 'Food'],
    shortDescription: 'Elegant, upscale website for fine dining restaurants and culinary experiences.',
    thumbnail: imgDiningRestaurant,
    demoUrl: `${BASE}templates/spa/dinig-restaurant.html`,
    type: 'spa-html',
    popularity: 90,
    createdAt: '2026-04-18',
    recommended: true,
  },
  {
    id: 'fitness-trainer',
    title: 'Personal Fitness Trainer',
    category: 'Business Templates',
    filterCategory: 'Business',
    tags: ['Business', 'Fitness', 'Health', 'Training'],
    shortDescription: 'Energetic, motivational website for personal trainers and fitness coaches.',
    thumbnail: imgFitnessTrainer,
    demoUrl: `${BASE}templates/spa/fitness-trainer.html`,
    type: 'spa-html',
    popularity: 86,
    createdAt: '2026-04-18',
    recommended: false,
  },

  // ── Services ─────────────────────────────────────────────────────────────
  {
    id: 'real-estate-agent',
    title: 'Real Estate Agent',
    category: 'Services Templates',
    filterCategory: 'Services',
    tags: ['Services', 'Real Estate', 'Property', 'Luxury'],
    shortDescription: 'Sophisticated website for luxury real estate agents and property professionals.',
    thumbnail: imgRealEstateAgent,
    demoUrl: `${BASE}templates/spa/real-estate-agent.html`,
    type: 'spa-html',
    popularity: 93,
    createdAt: '2026-04-18',
    recommended: true,
  },
  {
    id: 'electrician-contractor',
    title: 'Electrician & Contractor',
    category: 'Services Templates',
    filterCategory: 'Services',
    tags: ['Services', 'Electrician', 'Contractor', 'Trades'],
    shortDescription: 'Professional website for licensed electricians and electrical contractors.',
    thumbnail: imgElectricianContractor,
    demoUrl: `${BASE}templates/spa/electrician-contractor.html`,
    type: 'spa-html',
    popularity: 78,
    createdAt: '2026-04-18',
    recommended: false,
  },
  {
    id: 'home-cleaning-service',
    title: 'Home Cleaning Service',
    category: 'Services Templates',
    filterCategory: 'Services',
    tags: ['Services', 'Cleaning', 'Home', 'Local'],
    shortDescription: 'Fresh, organized website for professional home and commercial cleaning services.',
    thumbnail: imgHomeCleaningService,
    demoUrl: `${BASE}templates/spa/home-cleaning-service.html`,
    type: 'spa-html',
    popularity: 80,
    createdAt: '2026-04-18',
    recommended: false,
  },
  {
    id: 'hvac-technician',
    title: 'HVAC Technician',
    category: 'Services Templates',
    filterCategory: 'Services',
    tags: ['Services', 'HVAC', 'Heating', 'Cooling'],
    shortDescription: 'Reliable, professional website for HVAC heating and cooling service providers.',
    thumbnail: imgHvacTechnician,
    demoUrl: `${BASE}templates/spa/hvac-technician.html`,
    type: 'spa-html',
    popularity: 76,
    createdAt: '2026-04-18',
    recommended: false,
  },
  {
    id: 'landscape-contractor',
    title: 'Landscape Contractor',
    category: 'Services Templates',
    filterCategory: 'Services',
    tags: ['Services', 'Landscaping', 'Hardscape', 'Outdoor'],
    shortDescription: 'Scenic website for professional landscaping and hardscape design contractors.',
    thumbnail: imgLandscapeContractor,
    demoUrl: `${BASE}templates/spa/landscape-contractor.html`,
    type: 'spa-html',
    popularity: 79,
    createdAt: '2026-04-18',
    recommended: false,
  },
  {
    id: 'luxury-plumbing',
    title: 'Luxury Plumbing Services',
    category: 'Services Templates',
    filterCategory: 'Services',
    tags: ['Services', 'Plumbing', 'Luxury', 'Home'],
    shortDescription: 'Premium website for high-end plumbing and home services professionals.',
    thumbnail: imgLuxuryPlumbing,
    demoUrl: `${BASE}templates/spa/luxury-plumbing.html`,
    type: 'spa-html',
    popularity: 77,
    createdAt: '2026-04-18',
    recommended: false,
  },
  {
    id: 'snow-removal',
    title: 'Snow Removal Service',
    category: 'Services Templates',
    filterCategory: 'Services',
    tags: ['Services', 'Snow Removal', 'Winter', 'Property Care'],
    shortDescription: 'Crisp, clear website for premium snow removal and winter property maintenance.',
    thumbnail: imgSnowRemoval,
    demoUrl: `${BASE}templates/spa/snow-removal.html`,
    type: 'spa-html',
    popularity: 74,
    createdAt: '2026-04-18',
    recommended: false,
  },
]

export function getTemplateById(id) {
  return templates.find((t) => t.id === id) || null
}
